import { Facebook, Instagram, YouTube } from "@mui/icons-material";

export const navLinks = [
  { text: "Home", path: "/#home" },
  { text: "Portfolio", path: "/portfolio/All" },
  { text: "About", path: "/About" },
  { text: "Contact", path: "/#contact" },
  { text: "Live Stream", path: "/livestream" },
];

export const followUs = [
  {
    name:"instagram",
    icon: Instagram,
    link: "https://www.instagram.com/onefocus.photography?igsh=MTZnMzhkd3k3NTJxaw==",
  },
  {
    name:"facebook",
    icon: Facebook,
    link: "https://www.facebook.com/share/18tbwQwcS2/?mibextid=wwXIfr",
  },
  {
    name: "youtube",
    icon: YouTube,
    link: "https://youtube.com/@onefocusphotography?si=Izb_ZB5NDiWFrnsr",
  },
  {
    name:"threads",
    type: "svg",
    icon: "/threads-app-icon.svg",
    link: "https://www.threads.net/@onefocus.photography?igshid=NTc4MTIwNjQ2YQ=="
     
  }];
export const portfolioCards = [
  {
    title: "Pre-Weddings",
    description: "This is the description for Portfolio Card 3.",
    image: "/IMG_0450.JPG",
  },
  {
    title: "Weddings",
    description: "This is the description for Portfolio Card 1.",
    image: "/IMG_3358.JPG",
  },
  {
    title: "Portraits",
    description: "This is the description for Portfolio Card 2.",
    image: "/IMG_0463.JPG",
  },
  {
    title: "Events",
    description: "This is the description for Portfolio Card 4.",
    image: "/DSC09731.JPG",
  },
  // {
  //   title: "Reels",
  //   description: "This is the description for Portfolio Card 4.",
  //   image: "/DSC09731.JPG",
  // }
];

export const PreWeddingPhotos = [
  "/pre-wedding/PBC0394.JPG",
  "/pre-wedding/PBC0443.JPG",
  "/pre-wedding/PBC0449.JPG",
  "/pre-wedding/PBC0748.JPG",
  "/pre-wedding/PBC0767.JPG",
  "/pre-wedding/PBC0779.JPG",
  "/pre-wedding/PBC0790.JPG",
  "/pre-wedding/PBC0801.JPG",
  "/pre-wedding/PBC0814.JPG",
  "/pre-wedding/PBC0821.JPG",
  "/pre-wedding/PBC0832.JPG",
];

export const WeddingsPhotos = [
  "/weddings/PBC1675.JPG",
  "/weddings/PBC1699.JPG",
  "/weddings/PBC1727.JPG",
  "/weddings/PBC1847.JPG",
  "/weddings/PBC1860.JPG",
  "/weddings/PBC1862.JPG",
  "/weddings/PBC1999.JPG"
];

export const PortraitsPhotos = ['/portrait/IMG_0440.JPG','/portrait/IMG_0442.JPG','/portrait/IMG_0443.JPG','/portrait/IMG_0445.JPG','/portrait/IMG_0463.JPG'];

export const EventsPhotos = [
  "/CORATE/DSC09405.JPG",
  "/CORATE/DSC09452.JPG",
  "/CORATE/DSC09459.JPG",
  "/CORATE/DSC09496.JPG",
  "/CORATE/DSC09502.JPG",
  "/CORATE/DSC09530.JPG",
  "/CORATE/DSC09606.JPG",
  "/CORATE/DSC09666.JPG",
  "/CORATE/DSC09740.JPG",
  "/CORATE/DSC09744.JPG",
  "/CORATE/DSC09751.JPG",
  "/CORATE/DSC09798.JPG",
  "/CORATE/DSC09927.JPG",
];

export const countryCodes = [
  { country: "AF", code: "+93" },
  { country: "AL", code: "+355" },
  { country: "DZ", code: "+213" },
  { country: "AD", code: "+376" },
  { country: "AO", code: "+244" },
  { country: "AR", code: "+54" },
  { country: "AM", code: "+374" },
  { country: "AU", code: "+61" },
  { country: "AT", code: "+43" },
  { country: "AZ", code: "+994" },
  { country: "BH", code: "+973" },
  { country: "BD", code: "+880" },
  { country: "BY", code: "+375" },
  { country: "BE", code: "+32" },
  { country: "BZ", code: "+501" },
  { country: "BJ", code: "+229" },
  { country: "BT", code: "+975" },
  { country: "BO", code: "+591" },
  { country: "BA", code: "+387" },
  { country: "BW", code: "+267" },
  { country: "BR", code: "+55" },
  { country: "BN", code: "+673" },
  { country: "BG", code: "+359" },
  { country: "BF", code: "+226" },
  { country: "KH", code: "+855" },
  { country: "CM", code: "+237" },
  { country: "CA", code: "+1" },
  { country: "CL", code: "+56" },
  { country: "CN", code: "+86" },
  { country: "CO", code: "+57" },
  { country: "CR", code: "+506" },
  { country: "HR", code: "+385" },
  { country: "CU", code: "+53" },
  { country: "CY", code: "+357" },
  { country: "CZ", code: "+420" },
  { country: "DK", code: "+45" },
  { country: "DO", code: "+1-809" },
  { country: "EG", code: "+20" },
  { country: "EE", code: "+372" },
  { country: "ET", code: "+251" },
  { country: "FI", code: "+358" },
  { country: "FR", code: "+33" },
  { country: "GE", code: "+995" },
  { country: "DE", code: "+49" },
  { country: "GH", code: "+233" },
  { country: "GR", code: "+30" },
  { country: "GT", code: "+502" },
  { country: "HK", code: "+852" },
  { country: "HU", code: "+36" },
  { country: "IS", code: "+354" },
  { country: "IN", code: "+91" },
  { country: "ID", code: "+62" },
  { country: "IR", code: "+98" },
  { country: "IQ", code: "+964" },
  { country: "IE", code: "+353" },
  { country: "IL", code: "+972" },
  { country: "IT", code: "+39" },
  { country: "JM", code: "+1-876" },
  { country: "JP", code: "+81" },
  { country: "JO", code: "+962" },
  { country: "KE", code: "+254" },
  { country: "KR", code: "+82" },
  { country: "KW", code: "+965" },
  { country: "LA", code: "+856" },
  { country: "LV", code: "+371" },
  { country: "LB", code: "+961" },
  { country: "MY", code: "+60" },
  { country: "MV", code: "+960" },
  { country: "MX", code: "+52" },
  { country: "MC", code: "+377" },
  { country: "MN", code: "+976" },
  { country: "MA", code: "+212" },
  { country: "MM", code: "+95" },
  { country: "NP", code: "+977" },
  { country: "NL", code: "+31" },
  { country: "NZ", code: "+64" },
  { country: "NG", code: "+234" },
  { country: "NO", code: "+47" },
  { country: "OM", code: "+968" },
  { country: "PK", code: "+92" },
  { country: "PA", code: "+507" },
  { country: "PE", code: "+51" },
  { country: "PH", code: "+63" },
  { country: "PL", code: "+48" },
  { country: "PT", code: "+351" },
  { country: "QA", code: "+974" },
  { country: "RO", code: "+40" },
  { country: "RU", code: "+7" },
  { country: "SA", code: "+966" },
  { country: "SG", code: "+65" },
  { country: "ZA", code: "+27" },
  { country: "ES", code: "+34" },
  { country: "LK", code: "+94" },
  { country: "SE", code: "+46" },
  { country: "CH", code: "+41" },
  { country: "TW", code: "+886" },
  { country: "TH", code: "+66" },
  { country: "TR", code: "+90" },
  { country: "UA", code: "+380" },
  { country: "AE", code: "+971" },
  { country: "GB", code: "+44" },
  { country: "US", code: "+1" },
  { country: "UY", code: "+598" },
  { country: "UZ", code: "+998" },
  { country: "VE", code: "+58" },
  { country: "VN", code: "+84" },
  { country: "YE", code: "+967" },
  { country: "ZM", code: "+260" },
  { country: "ZW", code: "+263" },
];

export const services = ["Wedding", "Portrait", "Events","Engagement","Pre-Wedding","Post-Wedding","others"];

export const hearaboutus =["Friend","Social Media","Google","Google Ads","Facebook Ads","Instagram Ads","Instagram","Facebook","Twitter","LinkedIn","Youtube","Other"];